image:
  file: .gitpod.Dockerfile

tasks:
  - name: Tailscale daemon
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: Tailscale
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        sudo -E tailscale up
      else
        VRepo=$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)
        sudo -E tailscale up --hostname "gitpod_github--$VRepo"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit
