image:
  file: .gitpod.Dockerfile

tasks:
  - name: Tailscale daemon
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled

  - name: Tailscale startup
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-workspace"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit

  - name: GDrive auth restore
    command: |
      if [ -n "${ELIEZEDECK_GDRIVE_AUTH_STATE}" ]; then
        mkdir -p ~/.gdrive
        echo "${ELIEZEDECK_GDRIVE_AUTH_STATE}" | tee ~/.gdrive/token_v2.json > /dev/null
      fi

      echo "$KEROZEN_MG20XX_SA" | docker login -u _json_key --password-stdin https://eu.gcr.io
      exit

vscode:
  extensions:
    - akosyakov.gitpod-monitor
    - mhutchie.git-graph
    - thinker.copy-as-snippet

    - github.copilot
