image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    before: |
      # Add useful commands into the Bash history to make it easier to run common commands
      echo 'k port-forward services/change-me 8080:8080 8081:8081 --address 0.0.0.0' > /home/gitpod/.bash_history
      echo 'k config get-contexts' >> /home/gitpod/.bash_history
      echo 'k config use-context ' >> /home/gitpod/.bash_history
      echo 'k rollout restart deployment ' >> /home/gitpod/.bash_history
      echo 'lsof -i ":8003"' >> /home/gitpod/.bash_history

  - name: Setup NodeJS
    before: |
      nvm install 14
      nvm alias default 14
      npm install -g npm
      echo "nvm use default 14" >> ~/.bashrc
    init: |
      # Preload NPM packages
      echo "Uncomment the yarn install or use npm install just below"
      #yarn install

  - name: Tailscale daemon
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled

  - name: Tailscale startup
    command: |
      if [ -n "${TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-workspace"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_ELIE_ZEDECK_WORKSPACE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit

  - name: GDrive auth restore
    command: |
      if [ -n "${ELIEZEDECK_GDRIVE_AUTH_STATE}" ]; then
        mkdir -p ~/.gdrive
        echo "${ELIEZEDECK_GDRIVE_AUTH_STATE}" | tee ~/.gdrive/token_v2.json > /dev/null
      fi

      echo "$KEROZEN_MG20XX_SA" | docker login -u _json_key --password-stdin https://eu.gcr.io
      exit

vscode:
  extensions:
    - akosyakov.gitpod-monitor
    - mhutchie.git-graph
    - thinker.copy-as-snippet

    - github.copilot
